workflows:
  android:
    name: Build APK for Android
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      - name: Build APK
        script: |
          eas build --platform android
